### ISSUE TITLE
Question: todo and difference with forked bundle

### ISSUE THREAD

**Issue by ph1823** [absolute-quantum/DoctrineEncryptBundle#51]
Hello, I was wondering, what's the difference between your bundle version and the one you forked? I'm not sure I saw it or that there is one.

And do you have any feature additions planned for this one or are you just updating the security?

Thank for your reply!

**Comment by absolute-quantum** [comment]
The original bundle is outdated and uses bad encryption methods like cbc

I'm not actively doing PHP dev anymore; but any pr's that have a general consensus of being good will be vetted and added to the codebase
